# Generated by Django 2.2.3 on 2019-07-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190727_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='title',
        ),
    ]
