# Generated by Django 2.2.3 on 2019-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'Upcoming'), (2, 'Ongoing'), (3, 'Successful')], default=1),
            preserve_default=False,
        ),
    ]
